#Base configurations
server:
    port: 9000

#Database configurations
spring: 
    datasource: 
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:~/bankdb
        username: banktestuser
        password: bhnNJtr^F^BvB6pe
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2: 
        console:
            enabled: true
            path: /h2-console

#Custom configurations
banktest:
    baseUrl: https://sandbox.platfr.io/api/gbs/banking/v4.0/accounts/
    saleRead: /balance
    transactionsRead: /transactions
    moneyTransfer: /payments/money-transfers
    authSchema: S2S
    apiKey: FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP